name: Deploy Vite App via SSH

# This workflow is triggered on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite application for production
      - name: Build project
        run: npm run build

      # Step 5: Copy the build output to the server via SCP
      - name: Deploy to server via SCP
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_TARGET_DIR: ${{ env.SSH_TARGET_DIR }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -P $SSH_PORT -r dist/* $SSH_USERNAME@$SSH_HOST:$SSH_TARGET_DIR
          rm key.pem


